<script type="text/javascript">
    (function ($) {
        //PRODUCT PAGE
//        $('#filed-rating').barrating({
//            theme: 'fontawesome-stars'
//        });
        $(window).load(function () {
            // The slider being synced must be initialized first
            $('#carousel-thumbnail').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: false,
                slideshow: false,
                itemWidth: 120,
                itemMargin: 30,
                asNavFor: '#slider-image-product'
            });

            $('#carousel-thumbnail-1').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: false,
                slideshow: false,
                itemWidth: 120,
                itemMargin: 30,
                asNavFor: '#slider-image-product'
            });

            $('#slider-image-product').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: false,
                slideshow: false,
                directionNav: false,
                sync: ".slide-image-product"
            });
        });

        $("#share").jsSocials({
            shares: ["twitter", "facebook", "googleplus", "linkedin", "pinterest"],
            url: "#",
            showLabel: true,
            shareIn: "blank",
            showCount: true,
            smallScreenWidth: 640,
            largeScreenWidth: 1024,
            resizeTimeout: 200
        });

        //END PRODUCT PAGE
    }(jQuery));
</script>